import React from "react";

const About = () => {
  return (
    <div className="container">
      <div className="py-4">
        <h1 align="center">About Page</h1><br></br>
        <p className="lead">
        When talking about collecting, storing, and analyzing data about your site or application users, 
        it is important to define what type of data we are referring to. In the broadest sense, 
        user data means any type of data generated by people interacting with your products. 
        This data can be divided into groups based on how it was collected.
        </p>
      </div>
    </div>
  );
};

export default About;